"""Tests for causal fidelity validation."""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from causalsynth.data.schema import CausalDAG, ValidationReport
from causalsynth.generation.sampler import generate_samples
from causalsynth.scm.builder import fit_scm
from causalsynth.validation.causal import validate_causal_fidelity
from causalsynth.validation.report import build_report


@pytest.fixture
def synth_df(health_df: pd.DataFrame, health_dag: CausalDAG) -> pd.DataFrame:
    """Synthetic data generated from the health SCM."""
    scm = fit_scm(health_df, health_dag)
    return generate_samples(scm, n_samples=len(health_df), seed=42)


class TestValidateCausalFidelity:
    def test_returns_validation_report(
        self, health_df: pd.DataFrame, synth_df: pd.DataFrame, health_dag: CausalDAG
    ) -> None:
        """validate_causal_fidelity returns a ValidationReport."""
        val = validate_causal_fidelity(health_df, synth_df, health_dag)
        report = build_report(val, health_dag)
        assert isinstance(report, ValidationReport)

    def test_fidelity_score_in_range(
        self, health_df: pd.DataFrame, synth_df: pd.DataFrame, health_dag: CausalDAG
    ) -> None:
        """Causal fidelity score is in [0, 1]."""
        val = validate_causal_fidelity(health_df, synth_df, health_dag)
        report = build_report(val, health_dag)
        assert 0.0 <= report.causal_fidelity_score <= 1.0

    def test_well_generated_data_passes(
        self, health_df: pd.DataFrame, synth_df: pd.DataFrame, health_dag: CausalDAG
    ) -> None:
        """Data generated by the SCM should achieve a PASSED verdict."""
        val = validate_causal_fidelity(health_df, synth_df, health_dag)
        report = build_report(val, health_dag)
        assert report.verdict in ("PASSED", "WARNING"), (
            f"Expected PASSED or WARNING, got {report.verdict}: {report.verdict_explanation}"
        )

    def test_random_data_has_low_fidelity(
        self, health_df: pd.DataFrame, health_dag: CausalDAG
    ) -> None:
        """Completely random data should fail or have low causal fidelity."""
        rng = np.random.default_rng(0)
        random_df = pd.DataFrame(
            rng.standard_normal((len(health_df), len(health_dag.nodes))),
            columns=health_dag.nodes,
        )
        val = validate_causal_fidelity(health_df, random_df, health_dag)
        report = build_report(val, health_dag)
        # Random data should not get a perfect score
        assert report.causal_fidelity_score < 1.0

    def test_ks_results_contain_all_variables(
        self, health_df: pd.DataFrame, synth_df: pd.DataFrame, health_dag: CausalDAG
    ) -> None:
        """KS test results include entries for all shared variables."""
        val = validate_causal_fidelity(health_df, synth_df, health_dag)
        report = build_report(val, health_dag)
        for node in health_dag.nodes:
            if node in health_df.columns and node in synth_df.columns:
                assert node in report.ks_test_results

    def test_verdict_is_valid_string(
        self, health_df: pd.DataFrame, synth_df: pd.DataFrame, health_dag: CausalDAG
    ) -> None:
        """Verdict is one of PASSED, WARNING, FAILED."""
        val = validate_causal_fidelity(health_df, synth_df, health_dag)
        report = build_report(val, health_dag)
        assert report.verdict in ("PASSED", "WARNING", "FAILED")
