"""Application configuration via Pydantic settings.

Reads from environment variables (prefixed CAUSALSYNTH_) and .env files.
"""

from __future__ import annotations

import logging
from functools import lru_cache
from typing import Optional

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

logger = logging.getLogger("causalsynth")

VALID_NOISE_TYPES = ("gaussian", "laplace", "uniform")


class CausalSynthSettings(BaseSettings):
    """Central configuration for CausalSynth.

    Values are loaded in this priority order:
    1. Explicit constructor arguments
    2. Environment variables (prefixed CAUSALSYNTH_)
    3. .env file in the working directory
    4. Built-in defaults
    """

    model_config = SettingsConfigDict(
        env_prefix="CAUSALSYNTH_",
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # Noise distribution applied to structural equations
    default_noise: str = Field(
        default="gaussian",
        description="Noise distribution for structural equations: 'gaussian', 'laplace', 'uniform'.",
    )

    # Number of synthetic samples generated by default
    n_samples: int = Field(
        default=1000,
        ge=1,
        description="Default number of synthetic samples to generate.",
    )

    # Random seed for reproducibility
    seed: int = Field(
        default=42,
        description="Random seed for all stochastic operations.",
    )

    # Differential privacy budget (None = disabled)
    privacy_epsilon: Optional[float] = Field(
        default=None,
        description="Differential privacy epsilon. None disables DP noise.",
    )

    # Log level
    log_level: str = Field(
        default="INFO",
        description="Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL.",
    )

    # API server settings
    api_host: str = Field(default="127.0.0.1", description="API server listen address.")
    api_port: int = Field(default=8000, description="API server listen port.")

    # ── Validators ────────────────────────────────────────────────────────────

    @field_validator("default_noise")
    @classmethod
    def _validate_noise(cls, v: str) -> str:
        v = v.lower()
        if v not in VALID_NOISE_TYPES:
            raise ValueError(
                f"Invalid noise type '{v}'. Must be one of: {VALID_NOISE_TYPES}"
            )
        return v

    @field_validator("log_level")
    @classmethod
    def _validate_log_level(cls, v: str) -> str:
        v = v.upper()
        if v not in ("DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"):
            raise ValueError(f"Invalid log level: {v}")
        return v

    @field_validator("privacy_epsilon")
    @classmethod
    def _validate_epsilon(cls, v: Optional[float]) -> Optional[float]:
        if v is not None and v <= 0:
            raise ValueError(f"privacy_epsilon must be > 0, got {v}")
        return v


# ── Singleton accessor ────────────────────────────────────────────────────────


@lru_cache(maxsize=1)
def get_settings() -> CausalSynthSettings:
    """Return the cached application settings singleton."""
    return CausalSynthSettings()


def configure_logging(settings: CausalSynthSettings | None = None) -> None:
    """Set up Python logging based on application settings."""
    settings = settings or get_settings()
    level = getattr(logging, settings.log_level, logging.INFO)

    logging.basicConfig(
        level=level,
        format="%(asctime)s | %(name)-16s | %(levelname)-7s | %(message)s",
        datefmt="%H:%M:%S",
    )
    # Quieten noisy third-party loggers
    for noisy in ("httpx", "httpcore", "urllib3", "matplotlib"):
        logging.getLogger(noisy).setLevel(logging.WARNING)

    logger.debug("CausalSynth logging configured at %s level", settings.log_level)
